### PR TITLE
Upstart init scripts and docs

### PR DESCRIPTION
**Pull request by ahmetb**
cc:@colemickens

### CODE REVIEW

**Comment by ahmetb** [comment]
actually I need to double check if the plugin drivers should start before or after `docker` service.

In any case the socket check might be necessary, though I'm not sure how can I do that with curl.

**Comment by colemickens** [comment]
If you just want to wait for the existence of the tcp socket file you create, you can just do it like docker, I don't think you need curl. https://github.com/docker/docker/blob/master/contrib/init/upstart/docker.conf#L60

**Comment by ahmetb** [comment]
Alright, removing `filesystem` from `start on` fixed it! Thanks @colemickens.

**Comment by ahmetb** [comment]
I'm not going to wait on socket creation to call it "started", because (1) that doesn't necessarily indicate handlers are up and running (2) apparently docker engine retries with exponential back-off for plugins, so it should essentially succeed pretty easily.

**Pull request merged**
